#!/bin/bash

if [ $# != 1 ] ; then
   echo Usage: $0 path/to/mozilla-central
   exit 1
fi

# The directory that contains this script.
WD="$(dirname "$0")"

MC="$1"

if [ ! -f "$MC"/config/rules.mk -o ! -f "$MC"/js/src/config/rules.mk ] ; then
    echo "$MC" does not seem to be a mozilla-central directory
    exit 1
fi

set -e

mkdir -p "$MC"/tools
mkdir -p "$MC"/js/src/tools

cp -r "$WD"/hackymake "$MC"/tools
cp -r "$WD"/hackymake "$MC"/js/src/tools

patch -d "$MC" --dry-run -s -f -p1 < "$WD"/rules.mk.patch || { echo Test patch failed, no reject generated.  Fix up rules.mk patch. ; exit 1 ; }

patch -d "$MC" -p1 < "$WD"/rules.mk.patch || { echo rules.mk.patch unexpectedly did not apply cleanly ; exit 1 ; }
patch -d "$MC"/js/src -p1 < "$WD"/rules.mk.patch || { echo rules.mk.patch unexpectedly did not apply cleanly in js/src ; exit 1 ; }

cp "$MC"/tools/hackymake/handle-win32-manifest.sh "$MC"/tools
cp "$MC"/tools/hackymake/handle-win32-manifest.sh "$MC"/js/src/tools

